type PartnerName = "junama";
type Partner = {
  feedUrl: string;
  categories: string[];
};

export const Junama: Partner = {
  feedUrl:
    "https://www.partner-ads.com/dk/feed_udlaes.php?partnerid=50033&bannerid=105813&feedid=3269",
  categories: [
    "Autostole",
    "Baby & Toddler > Baby Transport > Baby Strollers",
    "Basic V2 Junama kollektion",
  ],
};

export const partners: Record<PartnerName, Partner> = {
  junama: Junama,
};

export const Bibs: Partner = {
  feedUrl:
    "https://www.partner-ads.com/dk/feed_udlaes.php?partnerid=50033&bannerid=102750&feedid=3055",
  categories: [
    "Accessories Bundle",
    "Baby Bedding",
    "Baby Bitie",
    "Baby Bottle",
    "Baby Bottle Accessories",
    "Baby Bottle Sleeve",
    "Bandana Bib",
    "Bath Toys",
    "Bib & Clip Set",
    "Blanket",
    "Boheme bundle",
    "Booties",
    "Colour bundle",
    "Couture bundle",
    "Cuddle Cloth",
    "Cup Set",
    "Cutlery Set",
    "De Lux bundle",
    "Dinner Bib",
    "Dinner Set",
    "Gift Cards",
    "Gift Set",
    "Hoodie Towel",
    "Loops",
    "Loops Outlet",
    "Pacifier",
    "Pacifier Box",
    "Pacifier Case",
    "Pacifier Clip",
    "Pacifier Outlet",
    "Place Mat",
    "Poncho",
    "Rattle",
    "Spoon Set",
    "Supreme bundle",
    "Wash Cloth",
    "Wobbly Tower",
  ],
};

export const Kraes: Partner = {
  feedUrl:
    "https://www.partner-ads.com/dk/feed_udlaes.php?partnerid=50033&bannerid=91977&feedid=2415",
  categories: [
    "Babyserien",
    "Babyserien > K-serien > KRAES junior",
    "Babyserien > K-serien > KRAES junior > Ukategoriseret",
    "Babyserien > KRAES junior",
    "Babyserien > KRAES junior > KRAES pakker",
    "Babyserien > KRAES pakker",
    "Babyserien > Ukategoriseret",
    "K-serien",
    "K-serien > KRAES junior",
    "K-serien > KRAES pakker",
    "KRAES junior",
    "KRAES junior > KRAES pakker",
    "KRAES pakker",
    "Mini",
    "Ukategoriseret",
  ],
};

export const Zleepi: Partner = {
  feedUrl:
    "https://www.partner-ads.com/dk/feed_udlaes.php?partnerid=50033&bannerid=97595&feedid=2716",
  categories: [
    "Leje",
    "Slyngevugger",
    "Slyngevugger > Vuggemotor",
    "Slyngevugger > Vuggemotor > Tilbehør",
    "Tilbehør",
    "Tilbehør > Spisesæt",
    "Tilbehør > Sutter",
    "Tyngdepose",
    "Vuggemotor",
  ],
};

export const Kaereborn: Partner = {
  feedUrl: "",
  categories: [
    "AUTOSTOLE",
    "BAD & PLEJE",
    "BØRNEVÆRELSET",
    "Cykler",
    "GAVEKORT",
    "GRATIS BABYBOX",
    "Legetøj",
    "MÆRKER",
    "NYHEDER",
    "OUTLET",
    "SIKKERHED",
    "TRILLEBÅRE",
    "TØJ & UDSTYR",
    "MÅLTIDET",
    "AUTOSTOLE",
    "BIBS",
    "BIBS TILBEHØR",
    "SUTTEBOKSE",
    "BRYSTPUMPER",
    "HAGESMÆKKE",
    "CABRASS",
    "DBD PEEKABOO",
    "MIKK-LINE BASIC HAGESMÆKKE",
    "MIKK-LINE BASIC RUND",
    "MIKK-LINE BASIC SPIDS",
    "TINY TOT SPISESMÆK",
    "HØJSTOLE",
    "STOKKE STEPS",
    "STOKKE BUNDLES",
    "STOKKE STEPS BUNDLE",
    "STOKKE STEPS BABYHYNDER",
    "MADKASSER & DRINKEDUNKE",
    "DONE BY DEER MADKASSER",
    "PÅ FARTEN - I BILEN",
    "PÅ FARTEN - MED FLYVEREN",
    "SERVICE",
    "DÆKKESERVIETTER",
    "GURLI GRIS MELAMIN",
    "SIKKERHED",
    "BABYALARMER",
    "GITRE OG LÅGER",
    "HØREVÆRN",
    "SIKKERHED I HJEMMET",
    "SUTTEFLASKER OG TILBEHØR",
    "SUTTEKÆDER",
    "SUTTER",
    "BØRNETØJ & -SKO",
    "AMMEINDLÆG",
    "BADETØJ",
    "BADEBUKSER",
    "BØRNETØJ OG SKO",
    "BØRNETØJ & -SKO",
    "BØRNETØJ OG SKO",
    "FLYVERDRAGT",
    "FLYVERDRAGTE",
    "FUTTER",
    "GUMMISTØVLER",
    "FODTØJ",
    "GUMMISTØVLER",
    "MIKK-LINE GUMMISTØVLER",
    "HAGESMÆKKE",
    "GOD PRIS",
    "HUER",
    "BØRNETØJ OG SKO",
    "KNÆBESKYTTER",
    "LUFFER",
    "MIKK-LINE ULD LUFFER",
    "MIKK-LINE ULDDRAGT",
    "BØRNETØJ & -SKO",
    "REGNTØJ",
    "HUST & CLAIRE REGNSÆT",
    "BØRNETØJ OG SKO",
    "REGNTØJ",
    "MIKK-LINE REGNTØJ",
    "BØRNETØJ OG SKO",
    "STRØMPEBUKSER",
    "BØRNETØJ OG SKO",
    "STRØMPER",
    "BØRNETØJ OG SKO",
    "TERMOTØJ",
    "BØRNETØJ OG SKO",
    "MIKK-LINE TERMOTØJ",
    "TERMOTØJ",
    "MIKK-LINE THERMOTØJ",
    "BØRNETØJ OG SKO",
    "TILBUD",
    "GUMMISTØVLER",
    "FODTØJ",
    "GUMMISTØVLER",
    "TILBUD",
    "STØVLER",
    "FODTØJ",
    "SKO",
    "TØJ TIL MOR",
    "GRAVIDITETSUNDERTØJ",
    "AMME BH",
    "GRAVIDITETSUNDERTØJ",
    "UKATEGORISERET",
    "WEB ONLY",
    "PUSLETASKER",
    "EMMALJUNGA PUSLETASKER",
    "EMMALJUNGA PUSLETASKER OG ORGANISER",
    "PETUNIA PICKLE BOTTOM",
    "TILBEHØR TIL VOGNE",
    "BASSON NORDIC LITE",
    "NORDIC LUX",
    "TRILLE ROYAL",
    "MOBY",
    "VIKLER",
    "VOKSIPOSEN",
    "BESAFE+VOKSI",
    "VOKSI CLASSIC MINI",
    "VOKSI EXPLORER",
  ],
};
